---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - TV
  - Podcasts
  - 'App Store'
  - FaceTime
  - Maps
  - Mail
  - Messages
  - Photos
  - Contacts
  - FreeForm
  - Music
  - News
  - FaceTime 
  - Freeform
  - Reminders
  - Calendar
dockitems_persist:
- name: "Firefox"
  path: "/Applications/Firefox.app/"
  pos: 3
- name: "Visual Studio Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 4
- name: "Warp"
  path: "/Applications/Warp.app/"
  pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/adamcbowman/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Documents/gitrepos/dotfiles
dotfiles_files:
  - .zshrc
  - .vimrc
  - .kubectl_aliases

homebrew_installed_packages:
  - git
  - gh
  - go
  - nmap
  - node
  - nvm
  - cowsay
  - lolcat
  - kubernetes-cli
  - kubernetes-helm
  - kubectx
  - minikube
  - docker-desktop

homebrew_taps: [homebrew/cask-versions]

homebrew_cask_appdir: /Applications
homebrew_cask_apps: [firefox, firefox-developer-edition, google-chrome, docker, warp, lunar, raspberry-pi-imager, visual-studio-code, sublime-text]

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
